
import Footer from '@/components/Footer';
import Nav from "@/components/Nav";



const Home=()=>{
  return(
    <>
     <div className="allButFooter">
        <div>
        <Nav/>
        <div>Create your own Dictionary. And don't forget to feed the Cat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac placerat vestibulum lectus mauris ultrices eros in. Ut consequat semper viverra nam libero justo laoreet sit amet. Pharetra convallis posuere morbi leo urna molestie at. Id consectetur purus ut faucibus pulvinar elementum integer. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Congue mauris rhoncus aenean vel. Diam vulputate ut pharetra sit amet aliquam id diam. Vitae tortor condimentum lacinia quis. Potenti nullam ac tortor vitae purus. Id cursus metus aliquam eleifend mi in nulla. In hac habitasse platea dictumst quisque sagittis purus sit. Accumsan sit amet nulla facilisi. Et leo duis ut diam quam nulla porttitor massa id. Non pulvinar neque laoreet suspendisse interdum.

Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Proin sed libero enim sed faucibus turpis in. Adipiscing enim eu turpis egestas pretium aenean pharetra magna ac. Dolor sit amet consectetur adipiscing elit ut. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Sem fringilla ut morbi tincidunt augue. Sodales ut etiam sit amet nisl. Tempus quam pellentesque nec nam aliquam sem et. At volutpat diam ut venenatis tellus in metus vulputate. In iaculis nunc sed augue lacus viverra vitae congue eu. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Justo donec enim diam vulputate ut pharetra sit amet. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Fermentum posuere urna nec tincidunt praesent semper. At tempor commodo ullamcorper a lacus vestibulum. Nisi est sit amet facilisis. Non blandit massa enim nec.

Massa sed elementum tempus egestas sed sed. Sit amet aliquam id diam maecenas ultricies mi. Pulvinar mattis nunc sed blandit. Sollicitudin aliquam ultrices sagittis orci. Iaculis eu non diam phasellus vestibulum lorem sed. Ac auctor augue mauris augue neque gravida in. Amet nisl suscipit adipiscing bibendum est ultricies. Ac turpis egestas maecenas pharetra convallis. Blandit massa enim nec dui. Eget gravida cum sociis natoque penatibus et magnis. Ornare quam viverra orci sagittis. Nunc consequat interdum varius sit amet. Arcu non sodales neque sodales ut etiam sit. Vestibulum morbi blandit cursus risus at ultrices. Enim diam vulputate ut pharetra. Convallis a cras semper auctor neque vitae tempus quam. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo.

Eget nullam non nisi est sit amet facilisis magna etiam. Quis ipsum suspendisse ultrices gravida dictum fusce ut. Volutpat blandit aliquam etiam erat velit scelerisque. In cursus turpis massa tincidunt dui ut. Cursus in hac habitasse platea dictumst quisque sagittis purus. Mattis vulputate enim nulla aliquet. Ac orci phasellus egestas tellus rutrum tellus pellentesque. Imperdiet proin fermentum leo vel. Consectetur adipiscing elit ut aliquam purus sit. Porttitor eget dolor morbi non arcu. Lectus proin nibh nisl condimentum id venenatis a. Enim facilisis gravida neque convallis a. Est velit egestas dui id. Morbi blandit cursus risus at ultrices mi tempus. Vel risus commodo viverra maecenas. Curabitur gravida arcu ac tortor. Sit amet consectetur adipiscing elit ut aliquam. Aenean pharetra magna ac placerat vestibulum.

Integer quis auctor elit sed vulputate mi. Eget gravida cum sociis natoque penatibus et magnis. Turpis massa sed elementum tempus egestas sed sed risus. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Morbi tristique senectus et netus et malesuada fames ac. Amet consectetur adipiscing elit pellentesque. Felis imperdiet proin fermentum leo vel. Ornare suspendisse sed nisi lacus sed. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Sed faucibus turpis in eu. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Pharetra magna ac placerat vestibulum lectus. A scelerisque purus semper eget duis at tellus at urna. Egestas integer eget aliquet nibh praesent tristique magna sit amet.

Ut lectus arcu bibendum at varius vel pharetra. Ut lectus arcu bibendum at. Elit sed vulputate mi sit. Diam phasellus vestibulum lorem sed risus. Lectus proin nibh nisl condimentum id venenatis a condimentum vitae. Egestas sed sed risus pretium quam. Pharetra sit amet aliquam id diam maecenas ultricies. Senectus et netus et malesuada. Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. Commodo nulla facilisi nullam vehicula ipsum a arcu. Placerat in egestas erat imperdiet sed euismod nisi porta lorem. Et malesuada fames ac turpis egestas integer. Nec feugiat nisl pretium fusce id velit ut. Venenatis urna cursus eget nunc scelerisque. Felis eget nunc lobortis mattis aliquam faucibus purus in. Condimentum lacinia quis vel eros donec ac odio tempor orci. Pharetra pharetra massa massa ultricies. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Est ullamcorper eget nulla facilisi. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean.

Ac feugiat sed lectus vestibulum mattis ullamcorper. Egestas congue quisque egestas diam in arcu. Cursus risus at ultrices mi tempus imperdiet. Orci a scelerisque purus semper. Risus quis varius quam quisque id diam vel. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Et netus et malesuada fames ac turpis egestas. Bibendum neque egestas congue quisque. Eget arcu dictum varius duis at consectetur. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Varius morbi enim nunc faucibus a pellentesque sit amet. Enim nulla aliquet porttitor lacus. Orci dapibus ultrices in iaculis nunc. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Bibendum ut tristique et egestas quis ipsum. Massa enim nec dui nunc mattis. Netus et malesuada fames ac turpis egestas. Morbi tristique senectus et netus et malesuada fames ac turpis.

Integer enim neque volutpat ac tincidunt vitae semper quis lectus. Amet dictum sit amet justo. Viverra accumsan in nisl nisi scelerisque. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Diam sit amet nisl suscipit. Egestas purus viverra accumsan in. Arcu bibendum at varius vel. In nibh mauris cursus mattis. Aliquam etiam erat velit scelerisque in dictum. Lobortis mattis aliquam faucibus purus in massa tempor nec. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Cras semper auctor neque vitae tempus quam. Non arcu risus quis varius quam quisque. Purus sit amet volutpat consequat mauris nunc congue nisi. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Elementum nisi quis eleifend quam adipiscing. Convallis convallis tellus id interdum velit laoreet id donec ultrices. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Aenean euismod elementum nisi quis. Risus nullam eget felis eget nunc lobortis mattis.

In fermentum et sollicitudin ac. Eget velit aliquet sagittis id consectetur purus. Porta nibh venenatis cras sed felis eget velit. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Aliquam nulla facilisi cras fermentum odio eu feugiat. Sed blandit libero volutpat sed. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. Leo a diam sollicitudin tempor id. Cras semper auctor neque vitae tempus quam pellentesque nec. Suspendisse faucibus interdum posuere lorem ipsum. Nunc mattis enim ut tellus elementum sagittis vitae et. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Arcu cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at. Nibh praesent tristique magna sit amet purus.

Integer eget aliquet nibh praesent. Nec sagittis aliquam malesuada bibendum. Vivamus arcu felis bibendum ut tristique. Ultricies mi quis hendrerit dolor. Odio facilisis mauris sit amet massa. Aliquam nulla facilisi cras fermentum odio eu feugiat. Enim sit amet venenatis urna cursus eget nunc. Posuere morbi leo urna molestie at. Varius morbi enim nunc faucibus a pellentesque. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Leo a diam sollicitudin tempor. Viverra nam libero justo laoreet sit amet cursus sit amet.

Volutpat odio facilisis mauris sit amet massa vitae tortor. Fringilla urna porttitor rhoncus dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Non blandit massa enim nec dui nunc mattis enim. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Dictum sit amet justo donec. Gravida cum sociis natoque penatibus et. Adipiscing elit ut aliquam purus sit amet luctus venenatis. Scelerisque in dictum non consectetur a erat nam at. Ullamcorper malesuada proin libero nunc consequat interdum varius sit. Sit amet nulla facilisi morbi. Molestie at elementum eu facilisis sed odio. Ipsum dolor sit amet consectetur adipiscing.

Faucibus pulvinar elementum integer enim neque volutpat. Pharetra magna ac placerat vestibulum lectus mauris. Non curabitur gravida arcu ac. Commodo sed egestas egestas fringilla phasellus faucibus. Hendrerit gravida rutrum quisque non tellus orci. Egestas quis ipsum suspendisse ultrices gravida dictum. Vestibulum morbi blandit cursus risus at. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Auctor elit sed vulputate mi sit amet mauris commodo. Blandit massa enim nec dui nunc mattis enim ut. Venenatis a condimentum vitae sapien pellentesque. Faucibus in ornare quam viverra orci. Porttitor leo a diam sollicitudin tempor id eu. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Vel eros donec ac odio tempor orci dapibus ultrices in.

Pretium vulputate sapien nec sagittis. Turpis massa sed elementum tempus egestas sed sed risus. Dignissim suspendisse in est ante in nibh mauris cursus. Sit amet tellus cras adipiscing enim eu turpis egestas pretium. Donec ac odio tempor orci dapibus ultrices in. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Purus ut faucibus pulvinar elementum integer enim. Eget gravida cum sociis natoque penatibus et. In pellentesque massa placerat duis. Enim facilisis gravida neque convallis a cras semper. Blandit aliquam etiam erat velit scelerisque in dictum. Congue mauris rhoncus aenean vel elit. Congue mauris rhoncus aenean vel elit. Risus sed vulputate odio ut. Mattis pellentesque id nibh tortor id aliquet lectus proin. Orci ac auctor augue mauris. Libero justo laoreet sit amet cursus sit amet dictum sit. Diam vel quam elementum pulvinar etiam non quam. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu.

Nisl nunc mi ipsum faucibus vitae aliquet nec. Neque convallis a cras semper. Lorem donec massa sapien faucibus et molestie ac. Diam volutpat commodo sed egestas egestas fringilla. Ac turpis egestas integer eget aliquet. Vulputate odio ut enim blandit. Ipsum dolor sit amet consectetur. Urna nunc id cursus metus aliquam eleifend mi in. Scelerisque eu ultrices vitae auctor. Sit amet cursus sit amet dictum sit amet justo donec. Tortor condimentum lacinia quis vel eros donec. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Ultrices gravida dictum fusce ut placerat. Imperdiet proin fermentum leo vel orci.

Vitae congue mauris rhoncus aenean vel elit scelerisque. Vel facilisis volutpat est velit egestas dui id ornare. Enim diam vulputate ut pharetra sit amet aliquam id. At elementum eu facilisis sed. Arcu cursus vitae congue mauris rhoncus aenean vel. Eleifend quam adipiscing vitae proin. Odio ut enim blandit volutpat maecenas volutpat blandit. Id volutpat lacus laoreet non. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Purus in massa tempor nec feugiat nisl. Id neque aliquam vestibulum morbi blandit cursus. Adipiscing tristique risus nec feugiat in. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Tellus in metus vulputate eu scelerisque felis imperdiet. Viverra adipiscing at in tellus integer feugiat. Arcu risus quis varius quam quisque. Ac ut consequat semper viverra. </div>
     </div>
     </div>
    <Footer/>
    </>
   
  )
}
export const revalidate = 0;
export default Home;